### ISSUE TITLE
Develop process to add default ground elevation from USGS NED data

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/shape-sql-loader#1]

**Comment by trietmnj** [comment]
I should not have named this as an nsi tool. This CLI should be kept simple as a generalized tool, just read-in shapefile, dynamically determine data structure, and upload.

**Comment by HenryGeorgist** [comment]
I will disconnect it from the NSI projects

**Comment by trietmnj** [comment]
Let's bring this issue back. ogr2ogr can already do basic interfacing with the PostGIS database. This package goal is now to provide integrating with ogr2ogr and interfacing with the rest of the metadata in a new schema that can hold multiple atomized datasets.

**Comment by trietmnj** [comment]
Adding in elevations can fit in the overall framework as integration to the store interface

**Comment by trietmnj** [comment]
done ce1cbc4669562cf1bcaafe437678dceef65ac94e
